app:
  replicaCount: 1
  command: ["php", "artisan", "optimize", "&&", "php", "artisan", "octane:start", "--host=0.0.0.0", "--port=80"]
  migrate:
    enabled: true
    seed: false
  resources:
    requests:
      memory: 512Mi
      cpu: 5m
    limits:
      memory: 1024Mi
      cpu: 1000m
  pdb:
    minAvailable: 1
horizon:
  enabled: false
  replicaCount: 1
  resources:
    requests:
      memory: 20Mi
      cpu: 5m
    limits:
      memory: 500Mi
      cpu: 1000m
cron:
  resources:
    requests:
      memory: 20Mi
      cpu: 5m
    limits:
      memory: 500Mi
      cpu: 1000m
queue:
  replicaCount: 1
  resources:
    requests:
      memory: 20Mi
      cpu: 5m
    limits:
      memory: 500Mi
      cpu: 1000m
reverb:
  replicaCount: 1
  enabled: false
  resources:
    requests:
      memory: 20Mi
      cpu: 5m
    limits:
      memory: 500Mi
      cpu: 1000m

typesense:
  enabled: false
  replicaCount: 1
  image:
    repository: typesense/typesense
    tag: "27.1"
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: 512Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 500m
  storage:
    size: 10Gi
    storageClass: ""

# bitnami redis!
redis:
  enabled: false
  replicaCount: 1
  resources:
    requests:
      memory: 500Mi
      cpu: 0.05
    limits:
      memory: 2Gi
      cpu: 2

infisical:
  enabled: false
  hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local/api
  projectSlug: your-project-slug
  envSlug: dev
  secretsPath: "/"
  recursive: true
  credentialsRef:
    secretName: universal-auth-credentials
    secretNamespace: infisical
  managedSecretReference:
    secretName: managed-secret
    creationPolicy: "Owner"

ingress:
  host: ef-streaming.eurofurence.org
  pathPrefix: ""  # Set to "/your-app" to host under domain.com/your-app
  annotations: {}

image:
  repository: eurofurence/XXXXXXXX
  pullPolicy: IfNotPresent
  tag: edge