apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel.fullname" . }}-scheduler
  labels:
    app: {{ include "laravel.fullname" . }}-scheduler
    {{- include "laravel.labels" . | nindent 4 }}
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "laravel.fullname" . }}-scheduler
  template:
    metadata:
      name: {{ include "laravel.fullname" . }}-scheduler
      labels:
        app: {{ include "laravel.fullname" . }}-scheduler
    spec:
      restartPolicy: Always
      containers:
        - name: scheduler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - php
            - artisan
            - schedule:work
          envFrom:
            - secretRef:
                name: {{ include "laravel.managedSecretReferenceSecretName" . }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}